### ISSUE TITLE
ограниченное количество фото при отключении бесконечого скролла

### ISSUE THREAD

**Issue by natalypoida** [frontspot-workshop/fancy-gallery#1]
Привет! я отключила скролл, чтобы работала пагинация(может, это неправильно:)), но теперь выходит гораздо меньше картинок, чем то, количество, которое видно при запросе. Например, total картинок выходит чило больше 20 тысяч, а грузится только 6 страниц по 30 картинок. Есть варианты, чтобы подгружались все картинки до последней без бесконечного скролла?
Спасибо.

**Comment by natalypoida** [comment]
Исправила сама. Ошибка была в том, что не указала при расчете пагинации полученное число количества фото. Теперь появилась другая проблема. Если не справлюсь, спрошу вас. Спасибо.

**Comment by frontspot-workshop** [comment]
> Привет! я отключила скролл, чтобы работала пагинация(может, это неправильно:)), но теперь выходит гораздо меньше картинок, чем то, количество, которое видно при запросе. Например, total картинок выходит чило больше 20 тысяч, а грузится только 6 страниц по 30 картинок. Есть варианты, чтобы подгружались все картинки до последней без бесконечного скролла?
> Спасибо.

Привет! В данном задании бесконечный скролл должен быть отключен, так что это правильно.
