### ISSUE TITLE
useEffect issue

### ISSUE THREAD

**Issue by alhenk** [frontspot-workshop/fancy-gallery#12]
why I've got this warning:
Line 50:8:   React Hook useEffect has missing dependencies: 'fetchImages' and 'searchImages'. Either include them or remove the dependency array  react-hooks/exhaustive-deps
printWarnings @ webpackHotDevClient.js:138
handleWarnings @ webpackHotDevClient.js:143
push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:210

another question:
what is best practice to keep API ACCESS_KEY not in the source code?
BTW mine access key is not actual ;)

**Comment by denistelyuk** [comment]
I had this warning too. Fixed by moving function to useEffect hook. **Is it correct?**

https://stackoverflow.com/questions/55840294/how-to-fix-missing-dependency-warning-when-using-useeffect-react-hook

**Comment by frontspot-workshop** [comment]
> I had this warning too. Fixed by moving function to useEffect hook. **Is it correct?**
> 
> https://stackoverflow.com/questions/55840294/how-to-fix-missing-dependency-warning-when-using-useeffect-react-hook

In this case, yes.

**Comment by frontspot-workshop** [comment]
> why I've got this warning:
> Line 50:8: React Hook useEffect has missing dependencies: 'fetchImages' and 'searchImages'. Either include them or remove the dependency array react-hooks/exhaustive-deps
> printWarnings @ webpackHotDevClient.js:138
> handleWarnings @ webpackHotDevClient.js:143
> push../node_modules/react-dev-utils/webpackHotDevClient.js.connection.onmessage @ webpackHotDevClient.js:210
> 
> another question:
> what is best practice to keep API ACCESS_KEY not in the source code?
> BTW mine access key is not actual ;)

you can find answer here 
https://stackoverflow.com/questions/46838015/using-api-keys-in-a-react-app
https://create-react-app.dev/docs/adding-custom-environment-variables/

**Comment by frontspot-workshop** [comment]
> I had this warning too. Fixed by moving function to useEffect hook. **Is it correct?**
> 
> https://stackoverflow.com/questions/55840294/how-to-fix-missing-dependency-warning-when-using-useeffect-react-hook
