### ISSUE TITLE
Клонирование проекта

### ISSUE THREAD

**Issue by timurtokt** [frontspot-workshop/fancy-gallery#2]
Нам нужно клонировать master или workshop-1 branch?  не совсем понял. Разъясните пожалуйста

**Comment by frontspot-workshop** [comment]
> Нам нужно клонировать master или workshop-1 branch? не совсем понял. Разъясните пожалуйста

Нужно сделать форк репозитория к себе. Клонировать у себя можно или мастер или ветку. Если клонируете мастер, нужно локально сделать чекаут ветки workshop-1.
