### ISSUE TITLE
нужна помощь - не могу добавить code reviewers на pull request

### ISSUE THREAD

**Issue by kembek** [frontspot-workshop/fancy-gallery#4]
Всем привет, помогите пожалуйста с прикреплением code reviewers. Также в какую ветку создать pull request? Пока что я создал pull request, но без code reviewers https://github.com/frontspot-workshop/fancy-gallery/pull/3

**Comment by frontspot-workshop** [comment]
Добрый день! Пулл реквест в ветку workshop-1 можно создать. Меня можно добавить в качестве collaborator.

**Comment by kembek** [comment]
Отправил вам запрос на collaboration, можете пж принять запрос?

**Comment by kembek** [comment]
Спасибо что приняли запрос, но я не все равно не могу добавить вас в code reviewers

![image](https://user-images.githubusercontent.com/16439067/95299133-00224400-089f-11eb-8e5b-a4c3c4399764.png)

**Comment by frontspot-workshop** [comment]
Я добавила frontspot-workshop в reviewers, должно появиться

**Comment by kembek** [comment]
Спасибо! Появилось 👍 
![image](https://user-images.githubusercontent.com/16439067/95308626-f94dfe00-08ab-11eb-87be-02b594e6edf3.png)
